main, win: create test runner in windows
indutny/mini-test.c pull request #3
Opened 2017-05-07 13:18 UTC by refack

For this case, I could do it simpler the libuv (since the runner prints it's own errors)

2017-05-07 18:28 UTC, indutny requested changes
Few nits, otherwise LGTM. Thank you!

2017-05-07 18:28 UTC, indutny commented on mini-test.gyp
> +    "type": "static_library",
I'd rather keep it. Any point in dropping it?

2017-05-07 18:28 UTC, indutny commented on src/spawn-win.c
> +{
Style, please put `{` on the same line as `popen_complete`.

Let's make `popen_complete` static.

2017-05-07 18:28 UTC, indutny commented on include/mini/common.h
> +#define BUFSIZE 4096
I'd rather move `BUFSIZE` to some private file. This file is a public API.

2017-05-07 18:28 UTC, indutny commented on include/mini/common.h
> +#define ABORT abort()
There is no `abort` on Windows? How do they live?

2017-05-07 18:28 UTC, indutny commented on src/spawn-win.c
> +  //  BOOL WINAPI CreateProcess(
I know it sounds lame, but let's use `/* */` comments here for consistency.

2017-05-07 18:28 UTC, indutny commented on src/spawn-win.c
> +  CHECK_EQ(wait_ret, WAIT_OBJECT_0, "Process ended strange");
Does it happen on non-zero exit code?

2017-05-07 19:33 UTC, refack commented on mini-test.gyp
> +    "type": "static_library",
No, local code leak.

2017-05-07 19:36 UTC, refack commented on mini-test.gyp
> +    "type": "static_library",
I wanted to run "real" `GYP` to get Visual Studio project files 😞

2017-05-07 19:37 UTC, refack commented on src/spawn-win.c
> +{
Ack

2017-05-07 19:37 UTC, refack commented on src/spawn-win.c
> +  //  BOOL WINAPI CreateProcess(
NP

2017-05-07 19:43 UTC, refack commented on src/spawn-win.c
> +  CHECK_EQ(wait_ret, WAIT_OBJECT_0, "Process ended strange");
No, only on strage cases

Return code/value | Description |
----------------- | ----------- |
WAIT_ABANDONED 0x00000080L | The specified object is a mutex object that was not released by the thread that owned the mutex object before the owning thread terminated. Ownership of the mutex object is granted to the calling thread and the mutex state is set to nonsignaled. If the mutex was protecting persistent state information, you should check it for consistency.
WAIT_OBJECT_0 0x00000000L | The state of the specified object is signaled.
WAIT_TIMEOUT 0x00000102L | The time-out interval elapsed, and the object's state is nonsignaled.
WAIT_FAILED 0xFFFFFFFF | The function has failed. To get extended error information, call GetLastError.

2017-05-07 19:46 UTC, refack commented on include/mini/common.h
> +#define ABORT abort()
We have but it makes allot of noise (Tries to find a debugger and creates a useless coredump)

2017-05-07 19:46 UTC, refack commented on include/mini/common.h
> +#define BUFSIZE 4096
So to `src/spawn-win.c`

2017-05-07 19:50 UTC, refack commented
PTAL

2017-05-07 19:57 UTC, indutny approved these changes
One last nit, otherwise LGTM!

2017-05-07 19:57 UTC, indutny commented on src/spawn-win.c
> +/*
I'm sorry for nit-picking again. But could it be indented?

2017-05-07 19:57 UTC, indutny commented on src/spawn-win.c
> +  CHECK_EQ(wait_ret, WAIT_OBJECT_0, "Process ended strange");
ok. Thanks!

2017-05-07 20:10 UTC, refack commented on src/spawn-win.c
> +/*
Tried...

2017-05-10 21:22 UTC, indutny commented
Landed with fixes in cb2b17e . Thank you!

Would you care to check that my fixes didn't break anything on Windows?

2017-05-10 21:22 UTC, closed without merging

2017-05-10 21:26 UTC, refack commented
Works. Look at the diff, you just bunched the declarations... seems semantically equal.

2017-05-10 21:28 UTC, indutny commented
Thanks!